"use client";

import { FormEvent, useEffect, useState } from "react";
import { API, api } from "@/lib/api";

type Detection={type:string;label:string;person_id?:number;confidence:number;bbox:number[];alert_level:"NORMAL"|"ALERT";requires_human_verification?:boolean};
type ImageResult={status:string;processed_image_url:string;width:number;height:number;people_count:number;risk_object_count:number;alert_level:"NORMAL"|"ALERT";response_time_ms:number;person_detector_engine:string;risk_detector_engine:string;human_verification_required:boolean;detections:Detection[]};

export default function ImageAnalysisPage(){
  const [preview,setPreview]=useState("");const [result,setResult]=useState<ImageResult|null>(null);const [running,setRunning]=useState(false);const [error,setError]=useState("");
  useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
  async function analyze(e:FormEvent<HTMLFormElement>){e.preventDefault();setRunning(true);setError("");setResult(null);const form=new FormData(e.currentTarget);const file=form.get("file") as File;if(preview)URL.revokeObjectURL(preview);setPreview(URL.createObjectURL(file));try{setResult(await api<ImageResult>("/api/analyze-image",{method:"POST",body:form}));}catch(err){setError(err instanceof Error?err.message:"Image analysis failed");}finally{setRunning(false);}}
  return <main className="p-5 lg:p-7"><div className="mb-6"><p className="font-osd text-[10px] uppercase tracking-[.25em] text-osd">GPU still-image screening</p><h1 className="mt-1 font-display text-2xl font-semibold">Image Analysis</h1><p className="mt-1 text-sm text-muted">อัปโหลด JPG, PNG หรือ WebP เพื่อตรวจบุคคลและวัตถุที่อาจมีความเสี่ยง</p></div>
    <form onSubmit={analyze} noValidate className="mb-6 flex flex-wrap items-end gap-4 rounded-xl border border-panelborder bg-panel/90 p-5"><label className="min-w-[280px] flex-1 text-xs text-muted">ไฟล์ภาพ <span className="ml-1 text-[10px] text-muted/75">JPG, PNG หรือ WebP</span><input name="file" required type="file" accept="image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp" className="mt-2 block w-full rounded-lg border border-dashed border-panelborder bg-base/60 p-2 text-sm text-muted file:mr-3 file:rounded-md file:border file:border-osd/25 file:bg-osd/10 file:px-3 file:py-2 file:text-osd hover:border-osd/40"/></label><button disabled={running} aria-busy={running} className="min-h-11 rounded-lg bg-osd px-5 py-2.5 text-sm font-semibold text-base hover:bg-[#57dfcf] disabled:opacity-50">{running?"กำลังวิเคราะห์ด้วย GPU…":"วิเคราะห์รูปภาพ"}</button></form>
    {error&&<div className="mb-4 rounded border border-alert/40 bg-alert/10 p-3 text-sm text-alert">{error}</div>}
    {(preview||result)&&<div className="grid gap-5 xl:grid-cols-2"><section className="rounded-lg border border-panelborder bg-panel p-3"><div className="mb-2 font-osd text-[10px] uppercase tracking-widest text-muted">Original image</div>{preview&&<img src={preview} alt="Uploaded source" className="max-h-[620px] w-full rounded bg-black object-contain"/>}</section><section className="rounded-lg border border-panelborder bg-panel p-3"><div className="mb-2 flex justify-between font-osd text-[10px] uppercase tracking-widest text-muted"><span>Analyzed result</span>{result&&<span className={result.alert_level==="ALERT"?"text-alert":"text-osd"}>{result.alert_level}</span>}</div>{result?<img src={`${API}${result.processed_image_url}`} alt="Analyzed result" className="max-h-[620px] w-full rounded bg-black object-contain"/>:<div className="flex min-h-64 items-center justify-center text-sm text-muted">{running?"GPU is processing the image…":"Waiting for result"}</div>}</section></div>}
    {result&&<><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-4"><Metric label="People" value={result.people_count}/><Metric label="Potential risk" value={result.risk_object_count} alert={result.risk_object_count>0}/><Metric label="Response time" value={`${result.response_time_ms} ms`}/><Metric label="Resolution" value={`${result.width}×${result.height}`}/></div><div className="mt-4 rounded-lg border border-panelborder bg-panel p-4 text-xs text-muted">Person: <span className="text-ink">{result.person_detector_engine}</span><br/>Risk: <span className="text-ink">{result.risk_detector_engine}</span><br/><span className="text-watch">Potential-risk results require human verification and do not confirm that an object is a weapon.</span></div><div className="mt-4 overflow-x-auto rounded-lg border border-panelborder bg-panel"><table className="w-full min-w-[650px] text-left text-sm"><thead className="font-osd text-[10px] uppercase text-muted"><tr><th className="p-3">Type</th><th>Label</th><th>Confidence</th><th>Bounding box</th><th>Level</th></tr></thead><tbody>{result.detections.map((d,i)=><tr key={i} className="border-t border-panelborder"><td className="p-3">{d.type}</td><td>{d.person_id?`Person #${d.person_id}`:d.label}</td><td>{Math.round(d.confidence*100)}%</td><td className="font-osd text-xs">[{d.bbox.join(", ")}]</td><td className={d.alert_level==="ALERT"?"text-alert":"text-osd"}>{d.alert_level}</td></tr>)}</tbody></table>{!result.detections.length&&<div className="p-8 text-center text-sm text-muted">ไม่พบวัตถุในคลาสที่ระบบรองรับ</div>}</div></>}
  </main>;
}
function Metric({label,value,alert=false}:{label:string;value:string|number;alert?:boolean}){return <div className="rounded border border-panelborder bg-panel p-4"><div className="text-xs text-muted">{label}</div><div className={`mt-1 font-osd text-xl ${alert?"text-alert":"text-osd"}`}>{value}</div></div>}
