"use client";

import { useEffect, useMemo, useState } from "react";
import { API, api, EventItem, VideoSource } from "@/lib/api";

export default function EventsPage(){
  const [events,setEvents]=useState<EventItem[]>([]);const [videos,setVideos]=useState<VideoSource[]>([]);const [camera,setCamera]=useState("");const [type,setType]=useState("");const [level,setLevel]=useState("");const [review,setReview]=useState("");const [date,setDate]=useState("");const [reviewer,setReviewer]=useState("Authorized staff");const [error,setError]=useState("");
  useEffect(()=>{api<VideoSource[]>("/api/cameras").then(setVideos);},[]);
  function load(){const q=new URLSearchParams({limit:"500"});if(camera)q.set("camera_id",camera);if(type)q.set("event_type",type);if(level)q.set("alert_level",level);if(review)q.set("review_status",review);if(date){q.set("date_from",`${date}T00:00:00`);q.set("date_to",`${date}T23:59:59`);}api<EventItem[]>(`/api/events?${q}`).then(setEvents).catch(e=>setError(e.message));}
  useEffect(()=>{load();},[camera,type,level,review,date]);
  async function setStatus(id:number,status:"confirmed"|"rejected"){await api(`/api/events/${id}/review`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,reviewed_by:reviewer})});load();}
  const names=useMemo(()=>Object.fromEntries(videos.map(v=>[v.id,v.name])),[videos]);
  return <main className="p-5 lg:p-7"><div className="mb-6"><p className="font-osd text-[10px] uppercase tracking-[.25em] text-osd">Human verification queue</p><h1 className="mt-1 font-display text-2xl font-semibold">Event Log</h1><p className="mt-1 text-sm text-muted">AI-generated candidates from recorded MP4 — ไม่ใช่การยืนยันความผิดหรืออันตราย</p></div>
    <div className="mb-4 grid gap-2 rounded border border-panelborder bg-panel p-3 sm:grid-cols-3 xl:grid-cols-6"><select value={camera} onChange={e=>setCamera(e.target.value)} className="rounded border border-panelborder bg-base px-3 py-2 text-sm"><option value="">All videos</option>{videos.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)} className="rounded border border-panelborder bg-base px-3 py-2 text-sm"><option value="">All event types</option><option value="restricted_zone">Restricted zone</option><option value="loitering">Loitering</option><option value="risk_object">Potential risk object</option></select><select value={level} onChange={e=>setLevel(e.target.value)} className="rounded border border-panelborder bg-base px-3 py-2 text-sm"><option value="">All levels</option><option>WATCH</option><option>ALERT</option></select><select value={review} onChange={e=>setReview(e.target.value)} className="rounded border border-panelborder bg-base px-3 py-2 text-sm"><option value="">All reviews</option><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="rejected">Rejected / FP</option></select><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="rounded border border-panelborder bg-base px-3 py-2 text-sm"/><input value={reviewer} onChange={e=>setReviewer(e.target.value)} placeholder="Reviewer name" className="rounded border border-panelborder bg-base px-3 py-2 text-sm"/></div>
    {error&&<p className="mb-3 text-alert">{error}</p>}<div className="overflow-x-auto rounded-lg border border-panelborder bg-panel"><table className="w-full min-w-[1180px] text-left text-sm"><thead className="border-b border-panelborder font-osd text-[10px] uppercase tracking-widest text-muted"><tr><th className="p-3">Snapshot</th><th>Timestamp</th><th>Video / Time</th><th>Event</th><th>Person ID</th><th>Confidence</th><th>Response</th><th>Level</th><th>Human review</th></tr></thead><tbody>{events.map(e=><tr key={e.id} className="border-b border-panelborder last:border-0"><td className="p-2">{e.snapshot?<a href={`${API}${e.snapshot}`} target="_blank"><img src={`${API}${e.snapshot}`} alt="" className="h-14 w-24 rounded object-cover"/></a>:<div className="h-14 w-24 rounded bg-base"/>}</td><td className="font-osd text-xs text-muted">{new Date(e.timestamp).toLocaleString("th-TH")}</td><td>{names[e.camera_id]||`Video #${e.camera_id}`}<div className="font-osd text-[10px] text-muted">{e.video_seconds?.toFixed(2)??"—"}s</div></td><td className="capitalize">{e.event_type.replaceAll("_"," ")}</td><td className="font-osd">#{e.track_id??"—"}</td><td>{e.confidence==null?"—":`${Math.round(e.confidence*100)}%`}</td><td className="font-osd text-xs">{e.response_time_ms==null?"—":`${e.response_time_ms.toFixed(0)} ms`}</td><td><span className={`rounded px-2 py-1 font-osd text-[10px] ${e.alert_level==="ALERT"?"bg-alert/10 text-alert":"bg-watch/10 text-watch"}`}>{e.alert_level}</span></td><td>{e.review_status==="pending"?<div className="flex gap-1"><button onClick={()=>setStatus(e.id,"confirmed")} className="rounded bg-osd/10 px-2 py-1 text-[10px] text-osd">CONFIRM</button><button onClick={()=>setStatus(e.id,"rejected")} className="rounded bg-alert/10 px-2 py-1 text-[10px] text-alert">FALSE POSITIVE</button></div>:<div className={`text-xs ${e.review_status==="confirmed"?"text-osd":"text-alert"}`}>{e.review_status}<div className="text-[10px] text-muted">{e.reviewed_by}</div></div>}</td></tr>)}</tbody></table>{!events.length&&<div className="p-10 text-center text-sm text-muted">ไม่พบ Event ตาม Filter นี้</div>}</div>
  </main>;
}
