"use client";

import { MouseEvent, useEffect, useState } from "react";
import { API, api, VideoSource, Zone } from "@/lib/api";

export default function ZonesPage() {
  const [videos,setVideos]=useState<VideoSource[]>([]); const [videoId,setVideoId]=useState(0); const [zones,setZones]=useState<Zone[]>([]); const [points,setPoints]=useState<number[][]>([]); const [name,setName]=useState("Restricted area"); const [type,setType]=useState<"restricted"|"loitering">("restricted"); const [threshold,setThreshold]=useState(10); const [message,setMessage]=useState("");
  useEffect(()=>{api<VideoSource[]>("/api/cameras").then(v=>{setVideos(v);if(v[0])setVideoId(v[0].id);});},[]);
  useEffect(()=>{if(videoId)api<Zone[]>(`/api/zones?camera_id=${videoId}`).then(setZones);},[videoId]);
  function addPoint(e:MouseEvent<HTMLDivElement>){const r=e.currentTarget.getBoundingClientRect();setPoints(p=>[...p,[(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height]]);}
  async function save(){if(points.length<3){setMessage("Polygon ต้องมีอย่างน้อย 3 จุด");return;} await api("/api/zones",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({camera_id:videoId,name,polygon:points,zone_type:type,loitering_threshold:threshold})});setPoints([]);setMessage("บันทึก Zone แล้ว");setZones(await api<Zone[]>(`/api/zones?camera_id=${videoId}`));}
  async function remove(id:number){await api(`/api/zones/${id}`,{method:"DELETE"});setZones(await api<Zone[]>(`/api/zones?camera_id=${videoId}`));}
  return <main className="p-5 lg:p-7"><div className="mb-6"><p className="font-osd text-[10px] uppercase tracking-[.25em] text-osd">Spatial rules</p><h1 className="mt-1 font-display text-2xl font-semibold">Restricted Zone Editor</h1><p className="mt-1 text-sm text-muted">คลิกบนภาพเพื่อวาด Polygon ด้วยพิกัด normalized ซึ่งใช้กับทุกความละเอียด</p></div>
    <div className="grid gap-5 xl:grid-cols-[1.6fr_1fr]"><section><label className="mb-2 block text-xs text-muted">Video Source<select value={videoId} onChange={e=>{setVideoId(Number(e.target.value));setPoints([]);}} className="mt-1 w-full rounded border border-panelborder bg-panel px-3 py-2 text-ink">{videos.map(v=><option value={v.id} key={v.id}>{v.name} — {v.location}</option>)}</select></label>
      {videoId ? <div onClick={addPoint} className="relative cursor-crosshair overflow-hidden rounded-lg border border-panelborder bg-black"><img src={`${API}/api/cameras/${videoId}/preview`} alt="Video preview" className="block h-auto w-full"/><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="pointer-events-none absolute inset-0 h-full w-full"><polygon points={points.map(p=>`${p[0]*100},${p[1]*100}`).join(" ")} fill="rgba(255,100,112,.25)" stroke="#FF6470" strokeWidth=".6"/>{points.map((p,i)=><circle key={i} cx={p[0]*100} cy={p[1]*100} r="1" fill="#39D5C3"/>)}</svg></div>:<div className="rounded border border-dashed border-panelborder p-10 text-center text-muted">อัปโหลด MP4 ก่อนสร้าง Zone</div>}
      <div className="mt-2 flex gap-2"><button onClick={()=>setPoints(p=>p.slice(0,-1))} className="rounded border border-panelborder px-3 py-2 text-xs">UNDO POINT</button><button onClick={()=>setPoints([])} className="rounded border border-panelborder px-3 py-2 text-xs">RESET</button><span className="self-center text-xs text-muted">{points.length} points</span></div></section>
      <aside><div className="rounded-lg border border-panelborder bg-panel p-4"><h2 className="font-medium">Zone details</h2><label className="mt-3 block text-xs text-muted">Name<input value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full rounded border border-panelborder bg-base px-3 py-2 text-ink"/></label><label className="mt-3 block text-xs text-muted">Type<select value={type} onChange={e=>setType(e.target.value as typeof type)} className="mt-1 w-full rounded border border-panelborder bg-base px-3 py-2 text-ink"><option value="restricted">Restricted zone</option><option value="loitering">Loitering area</option></select></label><label className="mt-3 block text-xs text-muted">Loitering threshold (video seconds)<input type="number" min="1" value={threshold} onChange={e=>setThreshold(Number(e.target.value))} className="mt-1 w-full rounded border border-panelborder bg-base px-3 py-2 text-ink"/></label><button onClick={save} disabled={!videoId||points.length<3} className="mt-4 w-full rounded bg-osd px-4 py-2 text-sm font-semibold text-base disabled:opacity-40">SAVE POLYGON</button>{message&&<p className="mt-2 text-xs text-watch">{message}</p>}</div>
        <div className="mt-4 space-y-2"><h2 className="font-osd text-xs uppercase tracking-widest text-muted">Saved Zones</h2>{zones.map(z=><div key={z.id} className="rounded border border-panelborder bg-panel p-3"><div className="flex justify-between"><div><div className="text-sm">{z.name}</div><div className="text-xs text-muted">{z.zone_type} · {z.polygon.length} points · {z.loitering_threshold}s</div></div><button onClick={()=>remove(z.id)} className="text-xs text-alert">DELETE</button></div></div>)}</div>
      </aside></div></main>;
}
